name: Tweety Bird Cowsay

on:  
  push:
    branches:
      - main

jobs:
  create_artwork:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Download Tweety Bird Cowfile
        run: sudo curl -o /usr/share/cowsay/cows/tweety-bird.cow https://raw.githubusercontent.com/MeenalJy/cowsay/master/cows/tweety-bird.cow

      - name: Execute Cowsay CMD
        run: cowsay -f tweety-bird "Hello Musu, I'm Tweety Bird" >> tweety-bird.txt

      - name: Upload Tweety Bird text file
        uses: actions/upload-artifact@v3
        with:
          name: tweety-bird-text-file
          path: tweety-bird.txt

  test_artwork:
    runs-on: ubuntu-latest
    needs: create_artwork
    steps:
      - name: Download Tweety Bird text file
        uses: actions/download-artifact@v3
        with:
          name: tweety-bird-text-file

      - name: Test File Contents
        run: |
         if grep -q "tweety-bird" tweety-bird.txt; then
            echo "Tweety Bird found in file."
          else
            echo "Tweety Bird not found in file."
            exit 1
          fi

  deploy_artwork:
    runs-on: ubuntu-latest
    needs: test_artwork
    steps:
      - name: Download Tweety Bird text file
        uses: actions/download-artifact@v3
        with:
          name: tweety-bird-text-file

      - name: Read File
        run: cat tweety-bird.txt

      - name: Deploy
        run: echo "Deploying..."

