name: Tweety Bird ASCII Art

on:  
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install toilet
      run: sudo apt-get install toilet -y

    - name: Generate Tweety Bird ASCII Art
      run: toilet -f mono12 -F metal "Hello Musu, I'm Tweety!" >> tweety-bird.txt
    
    - name: Upload Tweety text file
      uses: actions/upload-artifact@v3
      with:
        name: tweety-bird-text-file
        path: tweety-bird.txt
 
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download Tweety text file
      uses: actions/download-artifact@v3
      with:
        name: tweety-bird-text-file
      
    - name: Test File Content
      run: grep -i "Hello Musu" tweety-bird.txt || echo "Tweety Bird ASCII art not found"

  deploy_job_3:
    needs: [test_job_2]
    runs-on: ubuntu-latest
    steps:
    - name: Download Tweety text file
      uses: actions/download-artifact@v3
      with:
        name: tweety-bird-text-file
        
    - name: Read File
      run: cat tweety-bird.txt
       
    - name: Deploy
      run: echo Deploying ... .. .

