name: My First ASCII Artwork

on:  
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
    
    - name: Download tweety-bird Cowfile
      run: sudo curl -o /usr/share/cowsay/cows/tweety-bird.cow https://github.com/MeenalJy/cowsay/blob/master/cows/tweety-bird.cow

    - name: Execute Cowsay CMD
      run: cowsay -f tweety-bird "Hello Musu, I'm tweety-bird" >> tweety-bird.txt
    
    - name: Upload tweety-bird text file
      uses: actions/upload-artifact@v3
      with:
        name: tweety-bird-text-file
        path: tweety-bird.txt
 
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download tweety-bird text file
      uses: actions/download-artifact@v3
      with:
        name: tweety-bird-text-file
      
    - name: Test File Exists
      run: grep -i "tweety-bird" tweety-bird.txt

  deploy_job_3:
    needs: [test_job_2]
    runs-on: ubuntu-latest
    steps:
    - name: Download tweety-bird text file
      uses: actions/download-artifact@v3
      with:
        name: tweety-bird-text-file
        
    - name: Read File
      run: cat tweety-bird.txt
       
    - name: Deploy
      run: echo Deploying ... .. .
